### ISSUE TITLE
Things someone has to do (prob berkie ngl)

### ISSUE THREAD

**Issue by TonybynMp4** [Qbox-project/qbx_core#55]
### The problem

Qbus/QBCore is shit

### Ideal solution

remaking the whole framework

### Alternative solutions

Remove useless tables from the database (cid, id and cleanup the metadata etc cauz i think there's some unused stuff in there too)
make the citizenid an incrementing number (after a while it's gonna be a long number so players shouldn't confuse it with their server id anyway, and fuck 'em if they're not dumb they'll find a way to call them different things)

ALSO

Use TXAdmin's bans (they're maintained and should be better than whatever qbcore had)

Maybe use other features of txadmin idk
(i know they can already be used anyway but not duplicating features and making use of them in the adminmenu for example can be a good thing i guess)

**Comment by MahesKanoko999** [comment]
wow, this sounds really good, if you really want to apply it like this, also give it to convert it because it will be very useful for those who have been using qbox for a long time, like just and already have a lot of table user players, it's impossible for me to reffound their data again, thank you
