### ISSUE TITLE
qbx-vehicle key problem

### ISSUE THREAD

**Issue by link00077** [Qbox-project/qbx_core#590]
### Summary

bug with acces to vehicles job like police or garbage

### Reproduction

when i acces to police garage or garbage for exp , its shows me this error

[script:qbx_vehicleke] SCRIPT ERROR: @qbx_vehiclekeys/server/keys.lua:89: attempt to index a nil value (field 'state')
[script:qbx_vehicleke] > [global chunk] (@qbx_police/server/main.lua:115)
[script:qbx_vehicleke] > handler (@ox_lib/imports/callback/server.lua:96)
[   script:qbx_police] SCRIPT ERROR: @qbx_police/server/main.lua:115: 
[   script:qbx_police]  An error occurred while calling export `GiveKeys` in resource `qbx_vehiclekeys`:
[   script:qbx_police]   nil
[   script:qbx_police]  ---
[   script:qbx_police] 

### Expected behavior

dont have the key of car 

### Actual behavior

need to unlock to use it

### Current Version

1.3.0

### Custom Resources

none

**Comment by mafewtm** [comment]
This issue has nothing to do with the core at all. This would have been better suited for the `qbx_vehiclekeys` resource or the two other resources you're reporting to have the same issue. Nevertheless, for qbx_police, this issue was fixed already (https://github.com/Qbox-project/qbx_police/commit/16ee559ca809c48622997661adb66cfe199808b8). Update the resource and it should be good.
